- name: Generic | Install kubernetes master
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: kubernetes-master-1.2.0-0.6.alpha1.git8632732.el7
    state: present
  notify:
    - restart daemons
- name: Generic | Install kubernetes node
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: kubernetes-node-1.2.0-0.6.alpha1.git8632732.el7
    state: present
  notify:
    - restart daemons
  when: networking == 'opencontrail'
