---

- name: set perms on /srv directory
  file: path=/srv mode=0777

- name: setup exports file
  template: src=etcexports.j2 dest=/etc/exports

- name: start nfs
  service: name=nfs-server state=started
