---
- name: CentOS | Install kubernetes node
  yum:
    name=kubernetes-node-1.2.0-0.6.alpha1.git8632732.el7
    state=present
  notify:
    - restart daemons

- name: Generic | Install cloud-utils
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cloud-utils
    state: latest
  when: not is_atomic
