- name: Generic | Install kubernetes node
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: kubernetes-node
    state: latest
  notify:
    - restart daemons

- name: Generic | Install cloud-utils
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cloud-utils
    state: latest
  when: not is_atomic
